"""Analysis spider: turn per-post metrics into actionable, honestly-qualified insights.

Engagement score per post = (likes*2 + comments*3 + reactions) / max(views, 10).
Each feature value (format, title shape, posting hour in Africa/Casablanca...) is
scored with shrinkage toward the global mean so tiny samples cannot dominate.
Below MIN_POSTS total the output says "collecting" and gives NO winners.
"""
import json, re, statistics, datetime as dt
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).parent
MIN_POSTS = 30        # total learnable posts before any recommendation is made
MIN_GROUP = 5         # posts per feature value before it can be called a winner
SHRINK = 5            # pseudo-observations pulling a group toward the global mean
MA_OFFSET = dt.timedelta(hours=1)  # Morocco is UTC+1 (no DST since 2018 except Ramadan; good enough for bucketing)


def score(r):
    return (r["likes"] * 2 + r["comments"] * 3 + r["reactions"]) / max(r["views"], 10)


def _parse(ts):
    ts = re.sub(r"\.(\d+)", lambda m: "." + m.group(1)[:6].ljust(6, "0"), ts.replace("Z", "+00:00"))
    return dt.datetime.fromisoformat(ts)


def features(r):
    t = r["title"].strip()
    words = t.split()
    h = (_parse(r["created_at"]) + MA_OFFSET).hour
    return {
        "format": r["kind"] + ("/series" if r["series"] else ""),
        "topic": r["topic"],
        "title_question": "question" if re.search(r"[?؟]", t) else "statement",
        "title_length": "short(<=3w)" if len(words) <= 3 else "medium(4-6w)" if len(words) <= 6 else "long(7w+)",
        "title_has_number": "number" if re.search(r"\d|واحد|جوج|تلاتة|تسعة|عشرة|مية", t) else "no_number",
        "post_hour": "night(0-5)" if h < 6 else "morning(6-11)" if h < 12 else "afternoon(12-17)" if h < 18 else "evening(18-23)",
    }


def analyze(latest_rows):
    learn = [r for r in latest_rows if not r["sponsored"] and not r["pinned"]]
    out = {"generated_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
           "posts_total": len(latest_rows), "posts_learnable": len(learn), "min_posts": MIN_POSTS}
    if not learn:
        out.update(status="collecting", note="no learnable posts yet", features={}, winners=[])
        return out
    g_mean = statistics.mean(score(r) for r in learn)
    groups = defaultdict(lambda: defaultdict(list))
    for r in learn:
        for k, v in features(r).items():
            groups[k][v].append(score(r))
    table, winners = {}, []
    for k, vals in groups.items():
        table[k] = {}
        for v, xs in vals.items():
            adj = (sum(xs) + SHRINK * g_mean) / (len(xs) + SHRINK)
            table[k][v] = {"n": len(xs), "adj_score": round(adj, 4), "raw_mean": round(statistics.mean(xs), 4)}
        ranked = sorted(((v, d) for v, d in table[k].items() if d["n"] >= MIN_GROUP), key=lambda x: -x[1]["adj_score"])
        if len(ranked) >= 2 and ranked[0][1]["adj_score"] > ranked[1][1]["adj_score"] * 1.15:
            winners.append({"feature": k, "value": ranked[0][0], "n": ranked[0][1]["n"],
                            "lift_vs_next": round(ranked[0][1]["adj_score"] / max(ranked[1][1]["adj_score"], 1e-9), 2)})
    out["global_mean_score"] = round(g_mean, 4)
    out["features"] = table
    out["top_posts"] = [{"id": r["id"], "title": r["title"], "views": r["views"], "score": round(score(r), 4)}
                        for r in sorted(learn, key=score, reverse=True)[:5]]
    if len(learn) < MIN_POSTS:
        out.update(status="collecting", winners=[],
                   note=f"{len(learn)}/{MIN_POSTS} learnable posts: no recommendations until enough data")
    else:
        out.update(status="ready", winners=winners)
    return out


def latest_snapshot(history_path=None):
    p = Path(history_path or HERE / "data" / "history.jsonl")
    latest = {}
    for line in p.read_text(encoding="utf-8").splitlines():
        if line.strip():
            d = json.loads(line)
            latest[d["id"]] = d  # later lines overwrite earlier
    return list(latest.values())


GUIDE_HEADER = "# Content guidance (auto-generated by the Development Team; do not edit)\n"


def write_outputs(result, out_dir=None):
    out_dir = Path(out_dir or HERE / "insights")
    out_dir.mkdir(exist_ok=True)
    (out_dir / "latest.json").write_text(json.dumps(result, ensure_ascii=False, indent=1), encoding="utf-8")
    lines = [GUIDE_HEADER, f"Status: {result['status']} ({result['posts_learnable']} learnable posts)\n"]
    if result["status"] == "ready" and result["winners"]:
        lines.append("Data-backed preferences (apply to new titles/hooks/schedule):")
        for w in result["winners"]:
            lines.append(f"- {w['feature']} = {w['value']} (n={w['n']}, {w['lift_vs_next']}x vs next best)")
    else:
        lines.append("Not enough data yet. Use default style; keep varying title shape, length and hour so data is informative.")
    (out_dir / "content_guidance.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_dir


def funnel_report(path=None):
    """v1.1: registered vs publishing creators vs viewer signals, latest + change since previous run."""
    p = Path(path or HERE / "data" / "funnel.jsonl")
    snaps = [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines() if l.strip()] if p.exists() else []
    if not snaps:
        return {"status": "no_data"}
    last, prev = snaps[-1], (snaps[-2] if len(snaps) > 1 else None)
    def d(a, b):
        return None if a is None or b is None else a - b
    out = {"latest": last, "snapshots": len(snaps), "target_publishing_creators": 1000,
           "progress_pct": round(100 * last["publishing_creators"] / 1000, 2)}
    if prev:
        out["since_previous"] = {"registered_accounts": d(last["registered_accounts"], prev["registered_accounts"]),
                                 "publishing_creators": d(last["publishing_creators"], prev["publishing_creators"]),
                                 "views": d(last["viewer"]["views"], prev["viewer"]["views"])}
    if last["registered_accounts"]:
        out["activation_rate"] = round(last["publishing_creators"] / last["registered_accounts"], 4)
    return out


def write_funnel(out_dir=None):
    rep = funnel_report()
    out_dir = Path(out_dir or HERE / "insights"); out_dir.mkdir(exist_ok=True)
    (out_dir / "funnel.json").write_text(json.dumps(rep, ensure_ascii=False, indent=1), encoding="utf-8")
    return rep


if __name__ == "__main__":
    res = analyze(latest_snapshot())
    write_outputs(res)
    rep = write_funnel()
    print("funnel:", rep.get("latest", {}).get("publishing_creators"), "publishing creators")
    print(res["status"], res["posts_learnable"], "learnable;", len(res["winners"]), "winners")
